### ISSUE TITLE
Can't re-run pipeline on my own PR

### ISSUE THREAD

**Issue by marcusboden** [spack/spack-bot#19]
Hi, I tried the re-run pipeline command in my own [PR](https://github.com/spack/spack/pull/24833), but it replied with:

> Sorry marcusboden, I cannot do that for you. Only users with write can make this request!

As I understand it, I should be able to do that on my own PR.

**Comment by tgamblin** [comment]
Yep I think we should modify the check to allow authors to do this as well.

**Comment by vsoch** [comment]
This should be fixed, thanks for reporting the issue @marcusboden !
